-- =============================================================================
-- Java/Spring Code Model — DB Schema
-- Compatible with: H2 2.x (default) and PostgreSQL 10+
--
-- All statements use IF NOT EXISTS — safe to run on every startup.
-- H2:         BIGINT GENERATED BY DEFAULT AS IDENTITY (ANSI SQL:2003)
-- PostgreSQL: same syntax works from version 10 onward.
--             For PostgreSQL 9.x use BIGSERIAL; see model-schema.sql.
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- PROJECT
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS project (
    project_root    VARCHAR(2000) NOT NULL,
    saved_at_millis BIGINT        NOT NULL,
    format_version  INT           NOT NULL DEFAULT 1,
    PRIMARY KEY (project_root)
);


-- ─────────────────────────────────────────────────────────────────────────────
-- STRUCTURAL LAYER
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS package (
    qualified_name VARCHAR(500)  NOT NULL,
    project_root   VARCHAR(2000) NOT NULL,
    PRIMARY KEY (qualified_name, project_root),
    FOREIGN KEY (project_root) REFERENCES project (project_root) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS type (
    qualified_name  VARCHAR(500)  NOT NULL,
    simple_name     VARCHAR(200)  NOT NULL,
    package_name    VARCHAR(500)  NOT NULL DEFAULT '',
    project_root    VARCHAR(2000) NOT NULL,
    kind            VARCHAR(20)   NOT NULL
        CHECK (kind IN ('CLASS','INTERFACE','ENUM','ANNOTATION','RECORD')),
    extends_type    VARCHAR(500),
    source_path     VARCHAR(2000),
    line_number     INT,
    PRIMARY KEY (qualified_name, project_root),
    FOREIGN KEY (project_root)               REFERENCES project (project_root) ON DELETE CASCADE,
    FOREIGN KEY (package_name, project_root) REFERENCES package (qualified_name, project_root)
);

CREATE TABLE IF NOT EXISTS type_annotation (
    type_qualified_name VARCHAR(500)  NOT NULL,
    project_root        VARCHAR(2000) NOT NULL,
    annotation_name     VARCHAR(200)  NOT NULL,
    PRIMARY KEY (type_qualified_name, project_root, annotation_name),
    FOREIGN KEY (type_qualified_name, project_root) REFERENCES type (qualified_name, project_root) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS type_implements (
    type_qualified_name VARCHAR(500)  NOT NULL,
    project_root        VARCHAR(2000) NOT NULL,
    interface_name      VARCHAR(500)  NOT NULL,
    PRIMARY KEY (type_qualified_name, project_root, interface_name),
    FOREIGN KEY (type_qualified_name, project_root) REFERENCES type (qualified_name, project_root) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS field (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    declaring_type VARCHAR(500)  NOT NULL,
    project_root   VARCHAR(2000) NOT NULL,
    name           VARCHAR(200)  NOT NULL,
    type_name      VARCHAR(500)  NOT NULL,
    FOREIGN KEY (declaring_type, project_root) REFERENCES type (qualified_name, project_root) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS method (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    declaring_type   VARCHAR(500)  NOT NULL,
    project_root     VARCHAR(2000) NOT NULL,
    name             VARCHAR(200)  NOT NULL,
    visibility       VARCHAR(20)   NOT NULL
        CHECK (visibility IN ('PUBLIC','PROTECTED','PACKAGE_PRIVATE','PRIVATE')),
    return_type_name VARCHAR(500),
    source_path      VARCHAR(2000),
    line_number      INT,
    FOREIGN KEY (declaring_type, project_root) REFERENCES type (qualified_name, project_root) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS method_parameter (
    method_id BIGINT       NOT NULL,
    position  INT          NOT NULL,
    type_name VARCHAR(500) NOT NULL,
    PRIMARY KEY (method_id, position),
    FOREIGN KEY (method_id) REFERENCES method (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS package_import (
    from_package VARCHAR(500)  NOT NULL,
    to_package   VARCHAR(500)  NOT NULL,
    project_root VARCHAR(2000) NOT NULL,
    PRIMARY KEY (from_package, to_package, project_root),
    FOREIGN KEY (from_package, project_root) REFERENCES package (qualified_name, project_root) ON DELETE CASCADE,
    FOREIGN KEY (to_package,   project_root) REFERENCES package (qualified_name, project_root) ON DELETE CASCADE
);


-- ─────────────────────────────────────────────────────────────────────────────
-- SPRING LAYER
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS spring_bean (
    type_qualified_name VARCHAR(500)  NOT NULL,
    project_root        VARCHAR(2000) NOT NULL,
    analyzed_at_millis  BIGINT,
    source_path         VARCHAR(2000),
    line_number         INT,
    PRIMARY KEY (type_qualified_name, project_root),
    FOREIGN KEY (type_qualified_name, project_root) REFERENCES type (qualified_name, project_root) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS spring_bean_stereotype (
    type_qualified_name VARCHAR(500)  NOT NULL,
    project_root        VARCHAR(2000) NOT NULL,
    stereotype          VARCHAR(100)  NOT NULL,
    PRIMARY KEY (type_qualified_name, project_root, stereotype),
    FOREIGN KEY (type_qualified_name, project_root) REFERENCES spring_bean (type_qualified_name, project_root) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bean_injection (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_qualified_name VARCHAR(500)  NOT NULL,
    project_root        VARCHAR(2000) NOT NULL,
    to_qualified_name   VARCHAR(500),
    to_type_simple_name VARCHAR(200),
    kind                VARCHAR(20)   NOT NULL
        CHECK (kind IN ('CONSTRUCTOR','FIELD','SETTER')),
    qualifier           VARCHAR(200),
    FOREIGN KEY (from_qualified_name, project_root) REFERENCES spring_bean (type_qualified_name, project_root) ON DELETE CASCADE
);


-- ─────────────────────────────────────────────────────────────────────────────
-- INDEXES
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_type_package          ON type                   (package_name, project_root);
CREATE INDEX IF NOT EXISTS idx_type_kind             ON type                   (kind, project_root);
CREATE INDEX IF NOT EXISTS idx_type_annotation_name  ON type_annotation        (annotation_name, project_root);
CREATE INDEX IF NOT EXISTS idx_field_type_name       ON field                  (type_name);
CREATE INDEX IF NOT EXISTS idx_method_name           ON method                 (name, project_root);
CREATE INDEX IF NOT EXISTS idx_bean_stereotype       ON spring_bean_stereotype (stereotype, project_root);
CREATE INDEX IF NOT EXISTS idx_injection_to_fqn      ON bean_injection         (to_qualified_name, project_root);
CREATE INDEX IF NOT EXISTS idx_injection_from        ON bean_injection         (from_qualified_name, project_root);
